### ISSUE TITLE
New error always giving 200 status

### ISSUE THREAD

**Issue by bgold0** [feathersjs/errors#114] opened 2018-06-22 17:06 UTC
When I do any error on the [example docs](https://docs.feathersjs.com/api/errors.html#examples) I always get a 200 status. Is this supposed to happen? I can't seem to figure out how to give a custom status number 400, etc without doing a custom error.

Can someone elaborate.

**Comment by daffl** [comment] 2018-06-24 19:42
Duplicate of https://github.com/feathersjs/docs/issues/1170

**Closed by daffl** 2018-06-24 19:42 UTC
